name: LockedIn
options:
  bundleIdPrefix: com.lockedin
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: ""
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"

targets:
  LockedIn:
    type: application
    platform: iOS
    sources:
      - path: LockedIn
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: al.akm.lockedin
        INFOPLIST_FILE: LockedIn/Info.plist
        CODE_SIGN_ENTITLEMENTS: LockedIn/LockedIn.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: LockedInWidget
        embed: true
      - sdk: WidgetKit.framework

  LockedInWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: LockedInWidget
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: al.akm.lockedin.widget
        INFOPLIST_FILE: LockedInWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: LockedInWidget/LockedInWidget.entitlements
    dependencies:
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
